spring.application.name=Ecommerce

server.port=8080

spring.datasource.url= jdbc:postgresql://localhost:5432/Ecommerce
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=KC7THw8pKwbMe30Z3wVRmxH9AqU5SKmuASDg4pfZddmA5OUa3sTjDBGZb/3acSvVR46OGkYyrwL7ojWHqtCFnA
jwt.expiration-ms=86400000
